package said.microgest.enums;

public enum Permissions {
    MANAGE_ADHERENTS,
    MANAGE_OPERATIONS,
    MANAGE_PRETS,
    MANAGE_AGENCES,
    MANAGE_USERS,
    MANAGE_SETTINGS,
    MANAGE_REMBOURSEMENTS,
    VIEW_EPARGNE,
    VIEW_DASHBOARD,
    VIEW_STATISTICS,
    VALIDATE_PRETS,
    EXPORT_REPORTS
}